name: Summary
on:
  pull_request:
    branches:
      - main
jobs:
  wait-for-triggered-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Wait for all triggered status checks
        uses: poseidon/wait-for-status-checks@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
