name: Summary
on:
  pull_request:
    branches:
      - main
jobs:
  wait-for-triggered-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Wait for all triggered status checks
        uses: poseidon/wait-for-status-checks@e7e24423722c5b8e97a6dd5848827d2a412f812d # v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore_pattern: ^codecov/.+
